version: 2
project_name: kbridge
before:
  hooks:
    - go mod tidy
builds:
  - id: kb
    main: ./cmd/kb
    binary: kb
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/why-xn/kbridge/internal/version.Version={{.Version}}
      - -X github.com/why-xn/kbridge/internal/version.Commit={{.ShortCommit}}
      - -X github.com/why-xn/kbridge/internal/version.Date={{.Date}}
archives:
  - id: kb
    formats: [tar.gz]
    name_template: "kb_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: "checksums.txt"
release:
  github:
    owner: why-xn
    name: kbridge
  draft: false
  prerelease: auto
changelog:
  disable: true
