// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentStatus represents the health status of an agent.
type AgentStatus int32

const (
	// AGENT_STATUS_UNKNOWN indicates status is not known.
	AgentStatus_AGENT_STATUS_UNKNOWN AgentStatus = 0
	// AGENT_STATUS_HEALTHY indicates the agent is functioning normally.
	AgentStatus_AGENT_STATUS_HEALTHY AgentStatus = 1
	// AGENT_STATUS_DEGRADED indicates the agent is running but experiencing issues.
	AgentStatus_AGENT_STATUS_DEGRADED AgentStatus = 2
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNKNOWN",
		1: "AGENT_STATUS_HEALTHY",
		2: "AGENT_STATUS_DEGRADED",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNKNOWN":  0,
		"AGENT_STATUS_HEALTHY":  1,
		"AGENT_STATUS_DEGRADED": 2,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// OutputType indicates the type of command output.
type OutputType int32

const (
	// OUTPUT_TYPE_UNKNOWN indicates output type is not known.
	OutputType_OUTPUT_TYPE_UNKNOWN OutputType = 0
	// OUTPUT_TYPE_STDOUT indicates standard output.
	OutputType_OUTPUT_TYPE_STDOUT OutputType = 1
	// OUTPUT_TYPE_STDERR indicates standard error.
	OutputType_OUTPUT_TYPE_STDERR OutputType = 2
)

// Enum value maps for OutputType.
var (
	OutputType_name = map[int32]string{
		0: "OUTPUT_TYPE_UNKNOWN",
		1: "OUTPUT_TYPE_STDOUT",
		2: "OUTPUT_TYPE_STDERR",
	}
	OutputType_value = map[string]int32{
		"OUTPUT_TYPE_UNKNOWN": 0,
		"OUTPUT_TYPE_STDOUT":  1,
		"OUTPUT_TYPE_STDERR":  2,
	}
)

func (x OutputType) Enum() *OutputType {
	p := new(OutputType)
	*p = x
	return p
}

func (x OutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (OutputType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x OutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputType.Descriptor instead.
func (OutputType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

// RegisterRequest is sent by the agent to register with central service.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_token is the pre-shared token used to authenticate the agent.
	AgentToken string `protobuf:"bytes,1,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	// cluster_name is the unique name identifying this cluster.
	ClusterName   string `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *RegisterRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

// RegisterResponse is returned after an agent registration attempt.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether registration was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// agent_id is a unique identifier assigned to this agent by central.
	// Used in subsequent Heartbeat and ExecuteCommand calls.
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// error_message contains details if registration failed.
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// HeartbeatRequest is sent periodically by the agent to maintain connection.
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id is the identifier assigned during registration.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// status indicates the current health status of the agent.
	Status        AgentStatus `protobuf:"varint,2,opt,name=status,proto3,enum=kbridge.agent.v1.AgentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNKNOWN
}

// HeartbeatResponse is returned in response to a heartbeat.
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// acknowledged indicates the heartbeat was received.
	Acknowledged bool `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// next_heartbeat_seconds indicates how long to wait before the next heartbeat.
	NextHeartbeatSeconds int64 `protobuf:"varint,2,opt,name=next_heartbeat_seconds,json=nextHeartbeatSeconds,proto3" json:"next_heartbeat_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetNextHeartbeatSeconds() int64 {
	if x != nil {
		return x.NextHeartbeatSeconds
	}
	return 0
}

// CommandRequest represents a kubectl command to execute on the agent.
type CommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id is a unique identifier for this command execution.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// agent_id identifies which agent should execute this command.
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// command is the kubectl command arguments (e.g., ["get", "pods", "-o", "wide"]).
	Command []string `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	// namespace is the Kubernetes namespace for the command (optional).
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// timeout_seconds is the maximum time to wait for command completion.
	TimeoutSeconds int32 `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// stdin is optional input to be piped to the command's standard input.
	// Used for commands like "kubectl apply -f -" that read from stdin.
	Stdin         []byte `protobuf:"bytes,6,opt,name=stdin,proto3" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommandRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CommandRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

// CommandResponse contains output from a command execution.
// Multiple responses may be streamed as output is generated.
type CommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id matches the request that generated this response.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// type indicates whether this is stdout or stderr output.
	Type OutputType `protobuf:"varint,2,opt,name=type,proto3,enum=kbridge.agent.v1.OutputType" json:"type,omitempty"`
	// data contains the raw output bytes.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// complete indicates this is the final response for this command.
	Complete bool `protobuf:"varint,4,opt,name=complete,proto3" json:"complete,omitempty"`
	// exit_code is the command's exit code (only set when complete=true).
	ExitCode int32 `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// error_message contains error details if the command failed to execute.
	ErrorMessage  string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandResponse) GetType() OutputType {
	if x != nil {
		return x.Type
	}
	return OutputType_OUTPUT_TYPE_UNKNOWN
}

func (x *CommandResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetPendingCommandsRequest is sent by the agent to poll for commands.
type GetPendingCommandsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id is the identifier assigned during registration.
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingCommandsRequest) Reset() {
	*x = GetPendingCommandsRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingCommandsRequest) ProtoMessage() {}

func (x *GetPendingCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingCommandsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingCommandsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetPendingCommandsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// GetPendingCommandsResponse contains any pending commands for the agent.
type GetPendingCommandsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// commands contains the list of pending commands to execute.
	Commands      []*CommandRequest `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingCommandsResponse) Reset() {
	*x = GetPendingCommandsResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingCommandsResponse) ProtoMessage() {}

func (x *GetPendingCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingCommandsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingCommandsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetPendingCommandsResponse) GetCommands() []*CommandRequest {
	if x != nil {
		return x.Commands
	}
	return nil
}

// SubmitCommandResultRequest is sent by the agent after executing a command.
type SubmitCommandResultRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id matches the command that was executed.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// stdout contains the standard output from the command.
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// stderr contains the standard error from the command.
	Stderr []byte `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// exit_code is the command's exit code.
	ExitCode int32 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// error_message contains error details if the command failed to execute.
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCommandResultRequest) Reset() {
	*x = SubmitCommandResultRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCommandResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCommandResultRequest) ProtoMessage() {}

func (x *SubmitCommandResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCommandResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitCommandResultRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitCommandResultRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubmitCommandResultRequest) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *SubmitCommandResultRequest) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *SubmitCommandResultRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SubmitCommandResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// SubmitCommandResultResponse confirms the result was received.
type SubmitCommandResultResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates the result was accepted.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCommandResultResponse) Reset() {
	*x = SubmitCommandResultResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCommandResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCommandResultResponse) ProtoMessage() {}

func (x *SubmitCommandResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCommandResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitCommandResultResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitCommandResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CentralStreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*CentralStreamMessage_Start
	//	*CentralStreamMessage_Cancel
	//	*CentralStreamMessage_Stdin
	//	*CentralStreamMessage_Resize
	//	*CentralStreamMessage_PfStart
	//	*CentralStreamMessage_PfOpen
	//	*CentralStreamMessage_PfData
	//	*CentralStreamMessage_PfClose
	Msg           isCentralStreamMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CentralStreamMessage) Reset() {
	*x = CentralStreamMessage{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CentralStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CentralStreamMessage) ProtoMessage() {}

func (x *CentralStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CentralStreamMessage.ProtoReflect.Descriptor instead.
func (*CentralStreamMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CentralStreamMessage) GetMsg() isCentralStreamMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *CentralStreamMessage) GetStart() *StartStream {
	if x != nil {
		if x, ok := x.Msg.(*CentralStreamMessage_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *CentralStreamMessage) GetCancel() *CancelStream {
	if x != nil {
		if x, ok := x.Msg.(*CentralStreamMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *CentralStreamMessage) GetStdin() *StdinData {
	if x != nil {
		if x, ok := x.Msg.(*CentralStreamMessage_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *CentralStreamMessage) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Msg.(*CentralStreamMessage_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *CentralStreamMessage) GetPfStart() *PortForwardStart {
	if x != nil {
		if x, ok := x.Msg.(*CentralStreamMessage_PfStart); ok {
			return x.PfStart
		}
	}
	return nil
}

func (x *CentralStreamMessage) GetPfOpen() *PfOpen {
	if x != nil {
		if x, ok := x.Msg.(*CentralStreamMessage_PfOpen); ok {
			return x.PfOpen
		}
	}
	return nil
}

func (x *CentralStreamMessage) GetPfData() *PfData {
	if x != nil {
		if x, ok := x.Msg.(*CentralStreamMessage_PfData); ok {
			return x.PfData
		}
	}
	return nil
}

func (x *CentralStreamMessage) GetPfClose() *PfClose {
	if x != nil {
		if x, ok := x.Msg.(*CentralStreamMessage_PfClose); ok {
			return x.PfClose
		}
	}
	return nil
}

type isCentralStreamMessage_Msg interface {
	isCentralStreamMessage_Msg()
}

type CentralStreamMessage_Start struct {
	Start *StartStream `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type CentralStreamMessage_Cancel struct {
	Cancel *CancelStream `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"`
}

type CentralStreamMessage_Stdin struct {
	Stdin *StdinData `protobuf:"bytes,3,opt,name=stdin,proto3,oneof"`
}

type CentralStreamMessage_Resize struct {
	Resize *Resize `protobuf:"bytes,4,opt,name=resize,proto3,oneof"`
}

type CentralStreamMessage_PfStart struct {
	PfStart *PortForwardStart `protobuf:"bytes,5,opt,name=pf_start,json=pfStart,proto3,oneof"`
}

type CentralStreamMessage_PfOpen struct {
	PfOpen *PfOpen `protobuf:"bytes,6,opt,name=pf_open,json=pfOpen,proto3,oneof"`
}

type CentralStreamMessage_PfData struct {
	PfData *PfData `protobuf:"bytes,7,opt,name=pf_data,json=pfData,proto3,oneof"`
}

type CentralStreamMessage_PfClose struct {
	PfClose *PfClose `protobuf:"bytes,8,opt,name=pf_close,json=pfClose,proto3,oneof"`
}

func (*CentralStreamMessage_Start) isCentralStreamMessage_Msg() {}

func (*CentralStreamMessage_Cancel) isCentralStreamMessage_Msg() {}

func (*CentralStreamMessage_Stdin) isCentralStreamMessage_Msg() {}

func (*CentralStreamMessage_Resize) isCentralStreamMessage_Msg() {}

func (*CentralStreamMessage_PfStart) isCentralStreamMessage_Msg() {}

func (*CentralStreamMessage_PfOpen) isCentralStreamMessage_Msg() {}

func (*CentralStreamMessage_PfData) isCentralStreamMessage_Msg() {}

func (*CentralStreamMessage_PfClose) isCentralStreamMessage_Msg() {}

type StartStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Tty           bool                   `protobuf:"varint,4,opt,name=tty,proto3" json:"tty,omitempty"`
	Rows          uint32                 `protobuf:"varint,5,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,6,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStream) Reset() {
	*x = StartStream{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStream) ProtoMessage() {}

func (x *StartStream) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStream.ProtoReflect.Descriptor instead.
func (*StartStream) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *StartStream) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartStream) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartStream) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StartStream) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *StartStream) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *StartStream) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type CancelStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelStream) Reset() {
	*x = CancelStream{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelStream) ProtoMessage() {}

func (x *CancelStream) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelStream.ProtoReflect.Descriptor instead.
func (*CancelStream) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CancelStream) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StdinData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdinData) Reset() {
	*x = StdinData{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdinData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdinData) ProtoMessage() {}

func (x *StdinData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdinData.ProtoReflect.Descriptor instead.
func (*StdinData) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *StdinData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StdinData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *Resize) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type AgentStreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentStreamMessage_Register
	//	*AgentStreamMessage_Output
	//	*AgentStreamMessage_Exit
	//	*AgentStreamMessage_PfReady
	//	*AgentStreamMessage_PfData
	//	*AgentStreamMessage_PfClose
	//	*AgentStreamMessage_PfConnError
	//	*AgentStreamMessage_PfSessionError
	Msg           isAgentStreamMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStreamMessage) Reset() {
	*x = AgentStreamMessage{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStreamMessage) ProtoMessage() {}

func (x *AgentStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStreamMessage.ProtoReflect.Descriptor instead.
func (*AgentStreamMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *AgentStreamMessage) GetMsg() isAgentStreamMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentStreamMessage) GetRegister() *StreamRegister {
	if x != nil {
		if x, ok := x.Msg.(*AgentStreamMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetOutput() *StreamOutput {
	if x != nil {
		if x, ok := x.Msg.(*AgentStreamMessage_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetExit() *StreamExit {
	if x != nil {
		if x, ok := x.Msg.(*AgentStreamMessage_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetPfReady() *PfReady {
	if x != nil {
		if x, ok := x.Msg.(*AgentStreamMessage_PfReady); ok {
			return x.PfReady
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetPfData() *PfData {
	if x != nil {
		if x, ok := x.Msg.(*AgentStreamMessage_PfData); ok {
			return x.PfData
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetPfClose() *PfClose {
	if x != nil {
		if x, ok := x.Msg.(*AgentStreamMessage_PfClose); ok {
			return x.PfClose
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetPfConnError() *PfConnError {
	if x != nil {
		if x, ok := x.Msg.(*AgentStreamMessage_PfConnError); ok {
			return x.PfConnError
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetPfSessionError() *PfSessionError {
	if x != nil {
		if x, ok := x.Msg.(*AgentStreamMessage_PfSessionError); ok {
			return x.PfSessionError
		}
	}
	return nil
}

type isAgentStreamMessage_Msg interface {
	isAgentStreamMessage_Msg()
}

type AgentStreamMessage_Register struct {
	Register *StreamRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentStreamMessage_Output struct {
	Output *StreamOutput `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type AgentStreamMessage_Exit struct {
	Exit *StreamExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

type AgentStreamMessage_PfReady struct {
	PfReady *PfReady `protobuf:"bytes,4,opt,name=pf_ready,json=pfReady,proto3,oneof"`
}

type AgentStreamMessage_PfData struct {
	PfData *PfData `protobuf:"bytes,5,opt,name=pf_data,json=pfData,proto3,oneof"`
}

type AgentStreamMessage_PfClose struct {
	PfClose *PfClose `protobuf:"bytes,6,opt,name=pf_close,json=pfClose,proto3,oneof"`
}

type AgentStreamMessage_PfConnError struct {
	PfConnError *PfConnError `protobuf:"bytes,7,opt,name=pf_conn_error,json=pfConnError,proto3,oneof"`
}

type AgentStreamMessage_PfSessionError struct {
	PfSessionError *PfSessionError `protobuf:"bytes,8,opt,name=pf_session_error,json=pfSessionError,proto3,oneof"`
}

func (*AgentStreamMessage_Register) isAgentStreamMessage_Msg() {}

func (*AgentStreamMessage_Output) isAgentStreamMessage_Msg() {}

func (*AgentStreamMessage_Exit) isAgentStreamMessage_Msg() {}

func (*AgentStreamMessage_PfReady) isAgentStreamMessage_Msg() {}

func (*AgentStreamMessage_PfData) isAgentStreamMessage_Msg() {}

func (*AgentStreamMessage_PfClose) isAgentStreamMessage_Msg() {}

func (*AgentStreamMessage_PfConnError) isAgentStreamMessage_Msg() {}

func (*AgentStreamMessage_PfSessionError) isAgentStreamMessage_Msg() {}

type StreamRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRegister) Reset() {
	*x = StreamRegister{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRegister) ProtoMessage() {}

func (x *StreamRegister) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRegister.ProtoReflect.Descriptor instead.
func (*StreamRegister) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *StreamRegister) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type StreamOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          OutputType             `protobuf:"varint,2,opt,name=type,proto3,enum=kbridge.agent.v1.OutputType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutput) Reset() {
	*x = StreamOutput{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutput) ProtoMessage() {}

func (x *StreamOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutput.ProtoReflect.Descriptor instead.
func (*StreamOutput) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *StreamOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamOutput) GetType() OutputType {
	if x != nil {
		return x.Type
	}
	return OutputType_OUTPUT_TYPE_UNKNOWN
}

func (x *StreamOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StreamExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamExit) Reset() {
	*x = StreamExit{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamExit) ProtoMessage() {}

func (x *StreamExit) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamExit.ProtoReflect.Descriptor instead.
func (*StreamExit) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *StreamExit) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StreamExit) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PortForwardStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Ports         []uint32               `protobuf:"varint,4,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardStart) Reset() {
	*x = PortForwardStart{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardStart) ProtoMessage() {}

func (x *PortForwardStart) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardStart.ProtoReflect.Descriptor instead.
func (*PortForwardStart) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *PortForwardStart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PortForwardStart) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *PortForwardStart) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PortForwardStart) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

type PfOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnId        uint32                 `protobuf:"varint,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	RemotePort    uint32                 `protobuf:"varint,3,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PfOpen) Reset() {
	*x = PfOpen{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PfOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PfOpen) ProtoMessage() {}

func (x *PfOpen) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PfOpen.ProtoReflect.Descriptor instead.
func (*PfOpen) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *PfOpen) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PfOpen) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *PfOpen) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

type PfData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnId        uint32                 `protobuf:"varint,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PfData) Reset() {
	*x = PfData{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PfData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PfData) ProtoMessage() {}

func (x *PfData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PfData.ProtoReflect.Descriptor instead.
func (*PfData) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *PfData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PfData) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *PfData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PfClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnId        uint32                 `protobuf:"varint,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PfClose) Reset() {
	*x = PfClose{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PfClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PfClose) ProtoMessage() {}

func (x *PfClose) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PfClose.ProtoReflect.Descriptor instead.
func (*PfClose) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *PfClose) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PfClose) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

type PfConnError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnId        uint32                 `protobuf:"varint,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PfConnError) Reset() {
	*x = PfConnError{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PfConnError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PfConnError) ProtoMessage() {}

func (x *PfConnError) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PfConnError.ProtoReflect.Descriptor instead.
func (*PfConnError) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *PfConnError) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PfConnError) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *PfConnError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PfReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PfReady) Reset() {
	*x = PfReady{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PfReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PfReady) ProtoMessage() {}

func (x *PfReady) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PfReady.ProtoReflect.Descriptor instead.
func (*PfReady) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

func (x *PfReady) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PfSessionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PfSessionError) Reset() {
	*x = PfSessionError{}
	mi := &file_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PfSessionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PfSessionError) ProtoMessage() {}

func (x *PfSessionError) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PfSessionError.ProtoReflect.Descriptor instead.
func (*PfSessionError) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *PfSessionError) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PfSessionError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x10kbridge.agent.v1\"[\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\vagent_token\x18\x01 \x01(\tR\n" +
	"agentToken\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterNameJ\x04\b\x03\x10\x04\"l\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"d\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.kbridge.agent.v1.AgentStatusR\x06status\"m\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x124\n" +
	"\x16next_heartbeat_seconds\x18\x02 \x01(\x03R\x14nextHeartbeatSeconds\"\xc1\x01\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x14\n" +
	"\x05stdin\x18\x06 \x01(\fR\x05stdin\"\xd4\x01\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.kbridge.agent.v1.OutputTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bcomplete\x18\x04 \x01(\bR\bcomplete\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"6\n" +
	"\x19GetPendingCommandsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"Z\n" +
	"\x1aGetPendingCommandsResponse\x12<\n" +
	"\bcommands\x18\x01 \x03(\v2 .kbridge.agent.v1.CommandRequestR\bcommands\"\xad\x01\n" +
	"\x1aSubmitCommandResultRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"7\n" +
	"\x1bSubmitCommandResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xda\x03\n" +
	"\x14CentralStreamMessage\x125\n" +
	"\x05start\x18\x01 \x01(\v2\x1d.kbridge.agent.v1.StartStreamH\x00R\x05start\x128\n" +
	"\x06cancel\x18\x02 \x01(\v2\x1e.kbridge.agent.v1.CancelStreamH\x00R\x06cancel\x123\n" +
	"\x05stdin\x18\x03 \x01(\v2\x1b.kbridge.agent.v1.StdinDataH\x00R\x05stdin\x122\n" +
	"\x06resize\x18\x04 \x01(\v2\x18.kbridge.agent.v1.ResizeH\x00R\x06resize\x12?\n" +
	"\bpf_start\x18\x05 \x01(\v2\".kbridge.agent.v1.PortForwardStartH\x00R\apfStart\x123\n" +
	"\apf_open\x18\x06 \x01(\v2\x18.kbridge.agent.v1.PfOpenH\x00R\x06pfOpen\x123\n" +
	"\apf_data\x18\a \x01(\v2\x18.kbridge.agent.v1.PfDataH\x00R\x06pfData\x126\n" +
	"\bpf_close\x18\b \x01(\v2\x19.kbridge.agent.v1.PfCloseH\x00R\apfCloseB\x05\n" +
	"\x03msg\"\x9e\x01\n" +
	"\vStartStream\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03tty\x18\x04 \x01(\bR\x03tty\x12\x12\n" +
	"\x04rows\x18\x05 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x06 \x01(\rR\x04cols\"-\n" +
	"\fCancelStream\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\">\n" +
	"\tStdinData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"O\n" +
	"\x06Resize\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\"\x81\x04\n" +
	"\x12AgentStreamMessage\x12>\n" +
	"\bregister\x18\x01 \x01(\v2 .kbridge.agent.v1.StreamRegisterH\x00R\bregister\x128\n" +
	"\x06output\x18\x02 \x01(\v2\x1e.kbridge.agent.v1.StreamOutputH\x00R\x06output\x122\n" +
	"\x04exit\x18\x03 \x01(\v2\x1c.kbridge.agent.v1.StreamExitH\x00R\x04exit\x126\n" +
	"\bpf_ready\x18\x04 \x01(\v2\x19.kbridge.agent.v1.PfReadyH\x00R\apfReady\x123\n" +
	"\apf_data\x18\x05 \x01(\v2\x18.kbridge.agent.v1.PfDataH\x00R\x06pfData\x126\n" +
	"\bpf_close\x18\x06 \x01(\v2\x19.kbridge.agent.v1.PfCloseH\x00R\apfClose\x12C\n" +
	"\rpf_conn_error\x18\a \x01(\v2\x1d.kbridge.agent.v1.PfConnErrorH\x00R\vpfConnError\x12L\n" +
	"\x10pf_session_error\x18\b \x01(\v2 .kbridge.agent.v1.PfSessionErrorH\x00R\x0epfSessionErrorB\x05\n" +
	"\x03msg\"+\n" +
	"\x0eStreamRegister\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"s\n" +
	"\fStreamOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.kbridge.agent.v1.OutputTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"m\n" +
	"\n" +
	"StreamExit\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"w\n" +
	"\x10PortForwardStart\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05ports\x18\x04 \x03(\rR\x05ports\"a\n" +
	"\x06PfOpen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\rR\x06connId\x12\x1f\n" +
	"\vremote_port\x18\x03 \x01(\rR\n" +
	"remotePort\"T\n" +
	"\x06PfData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\rR\x06connId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"A\n" +
	"\aPfClose\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\rR\x06connId\"[\n" +
	"\vPfConnError\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\rR\x06connId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"(\n" +
	"\aPfReady\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"E\n" +
	"\x0ePfSessionError\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\\\n" +
	"\vAgentStatus\x12\x18\n" +
	"\x14AGENT_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14AGENT_STATUS_HEALTHY\x10\x01\x12\x19\n" +
	"\x15AGENT_STATUS_DEGRADED\x10\x02*U\n" +
	"\n" +
	"OutputType\x12\x17\n" +
	"\x13OUTPUT_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12OUTPUT_TYPE_STDOUT\x10\x01\x12\x16\n" +
	"\x12OUTPUT_TYPE_STDERR\x10\x022\xfc\x03\n" +
	"\fAgentService\x12Q\n" +
	"\bRegister\x12!.kbridge.agent.v1.RegisterRequest\x1a\".kbridge.agent.v1.RegisterResponse\x12T\n" +
	"\tHeartbeat\x12\".kbridge.agent.v1.HeartbeatRequest\x1a#.kbridge.agent.v1.HeartbeatResponse\x12^\n" +
	"\n" +
	"OpenStream\x12$.kbridge.agent.v1.AgentStreamMessage\x1a&.kbridge.agent.v1.CentralStreamMessage(\x010\x01\x12o\n" +
	"\x12GetPendingCommands\x12+.kbridge.agent.v1.GetPendingCommandsRequest\x1a,.kbridge.agent.v1.GetPendingCommandsResponse\x12r\n" +
	"\x13SubmitCommandResult\x12,.kbridge.agent.v1.SubmitCommandResultRequest\x1a-.kbridge.agent.v1.SubmitCommandResultResponseB-Z+github.com/why-xn/kbridge/api/proto/agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_agent_proto_goTypes = []any{
	(AgentStatus)(0),                    // 0: kbridge.agent.v1.AgentStatus
	(OutputType)(0),                     // 1: kbridge.agent.v1.OutputType
	(*RegisterRequest)(nil),             // 2: kbridge.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),            // 3: kbridge.agent.v1.RegisterResponse
	(*HeartbeatRequest)(nil),            // 4: kbridge.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 5: kbridge.agent.v1.HeartbeatResponse
	(*CommandRequest)(nil),              // 6: kbridge.agent.v1.CommandRequest
	(*CommandResponse)(nil),             // 7: kbridge.agent.v1.CommandResponse
	(*GetPendingCommandsRequest)(nil),   // 8: kbridge.agent.v1.GetPendingCommandsRequest
	(*GetPendingCommandsResponse)(nil),  // 9: kbridge.agent.v1.GetPendingCommandsResponse
	(*SubmitCommandResultRequest)(nil),  // 10: kbridge.agent.v1.SubmitCommandResultRequest
	(*SubmitCommandResultResponse)(nil), // 11: kbridge.agent.v1.SubmitCommandResultResponse
	(*CentralStreamMessage)(nil),        // 12: kbridge.agent.v1.CentralStreamMessage
	(*StartStream)(nil),                 // 13: kbridge.agent.v1.StartStream
	(*CancelStream)(nil),                // 14: kbridge.agent.v1.CancelStream
	(*StdinData)(nil),                   // 15: kbridge.agent.v1.StdinData
	(*Resize)(nil),                      // 16: kbridge.agent.v1.Resize
	(*AgentStreamMessage)(nil),          // 17: kbridge.agent.v1.AgentStreamMessage
	(*StreamRegister)(nil),              // 18: kbridge.agent.v1.StreamRegister
	(*StreamOutput)(nil),                // 19: kbridge.agent.v1.StreamOutput
	(*StreamExit)(nil),                  // 20: kbridge.agent.v1.StreamExit
	(*PortForwardStart)(nil),            // 21: kbridge.agent.v1.PortForwardStart
	(*PfOpen)(nil),                      // 22: kbridge.agent.v1.PfOpen
	(*PfData)(nil),                      // 23: kbridge.agent.v1.PfData
	(*PfClose)(nil),                     // 24: kbridge.agent.v1.PfClose
	(*PfConnError)(nil),                 // 25: kbridge.agent.v1.PfConnError
	(*PfReady)(nil),                     // 26: kbridge.agent.v1.PfReady
	(*PfSessionError)(nil),              // 27: kbridge.agent.v1.PfSessionError
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: kbridge.agent.v1.HeartbeatRequest.status:type_name -> kbridge.agent.v1.AgentStatus
	1,  // 1: kbridge.agent.v1.CommandResponse.type:type_name -> kbridge.agent.v1.OutputType
	6,  // 2: kbridge.agent.v1.GetPendingCommandsResponse.commands:type_name -> kbridge.agent.v1.CommandRequest
	13, // 3: kbridge.agent.v1.CentralStreamMessage.start:type_name -> kbridge.agent.v1.StartStream
	14, // 4: kbridge.agent.v1.CentralStreamMessage.cancel:type_name -> kbridge.agent.v1.CancelStream
	15, // 5: kbridge.agent.v1.CentralStreamMessage.stdin:type_name -> kbridge.agent.v1.StdinData
	16, // 6: kbridge.agent.v1.CentralStreamMessage.resize:type_name -> kbridge.agent.v1.Resize
	21, // 7: kbridge.agent.v1.CentralStreamMessage.pf_start:type_name -> kbridge.agent.v1.PortForwardStart
	22, // 8: kbridge.agent.v1.CentralStreamMessage.pf_open:type_name -> kbridge.agent.v1.PfOpen
	23, // 9: kbridge.agent.v1.CentralStreamMessage.pf_data:type_name -> kbridge.agent.v1.PfData
	24, // 10: kbridge.agent.v1.CentralStreamMessage.pf_close:type_name -> kbridge.agent.v1.PfClose
	18, // 11: kbridge.agent.v1.AgentStreamMessage.register:type_name -> kbridge.agent.v1.StreamRegister
	19, // 12: kbridge.agent.v1.AgentStreamMessage.output:type_name -> kbridge.agent.v1.StreamOutput
	20, // 13: kbridge.agent.v1.AgentStreamMessage.exit:type_name -> kbridge.agent.v1.StreamExit
	26, // 14: kbridge.agent.v1.AgentStreamMessage.pf_ready:type_name -> kbridge.agent.v1.PfReady
	23, // 15: kbridge.agent.v1.AgentStreamMessage.pf_data:type_name -> kbridge.agent.v1.PfData
	24, // 16: kbridge.agent.v1.AgentStreamMessage.pf_close:type_name -> kbridge.agent.v1.PfClose
	25, // 17: kbridge.agent.v1.AgentStreamMessage.pf_conn_error:type_name -> kbridge.agent.v1.PfConnError
	27, // 18: kbridge.agent.v1.AgentStreamMessage.pf_session_error:type_name -> kbridge.agent.v1.PfSessionError
	1,  // 19: kbridge.agent.v1.StreamOutput.type:type_name -> kbridge.agent.v1.OutputType
	2,  // 20: kbridge.agent.v1.AgentService.Register:input_type -> kbridge.agent.v1.RegisterRequest
	4,  // 21: kbridge.agent.v1.AgentService.Heartbeat:input_type -> kbridge.agent.v1.HeartbeatRequest
	17, // 22: kbridge.agent.v1.AgentService.OpenStream:input_type -> kbridge.agent.v1.AgentStreamMessage
	8,  // 23: kbridge.agent.v1.AgentService.GetPendingCommands:input_type -> kbridge.agent.v1.GetPendingCommandsRequest
	10, // 24: kbridge.agent.v1.AgentService.SubmitCommandResult:input_type -> kbridge.agent.v1.SubmitCommandResultRequest
	3,  // 25: kbridge.agent.v1.AgentService.Register:output_type -> kbridge.agent.v1.RegisterResponse
	5,  // 26: kbridge.agent.v1.AgentService.Heartbeat:output_type -> kbridge.agent.v1.HeartbeatResponse
	12, // 27: kbridge.agent.v1.AgentService.OpenStream:output_type -> kbridge.agent.v1.CentralStreamMessage
	9,  // 28: kbridge.agent.v1.AgentService.GetPendingCommands:output_type -> kbridge.agent.v1.GetPendingCommandsResponse
	11, // 29: kbridge.agent.v1.AgentService.SubmitCommandResult:output_type -> kbridge.agent.v1.SubmitCommandResultResponse
	25, // [25:30] is the sub-list for method output_type
	20, // [20:25] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[10].OneofWrappers = []any{
		(*CentralStreamMessage_Start)(nil),
		(*CentralStreamMessage_Cancel)(nil),
		(*CentralStreamMessage_Stdin)(nil),
		(*CentralStreamMessage_Resize)(nil),
		(*CentralStreamMessage_PfStart)(nil),
		(*CentralStreamMessage_PfOpen)(nil),
		(*CentralStreamMessage_PfData)(nil),
		(*CentralStreamMessage_PfClose)(nil),
	}
	file_agent_proto_msgTypes[15].OneofWrappers = []any{
		(*AgentStreamMessage_Register)(nil),
		(*AgentStreamMessage_Output)(nil),
		(*AgentStreamMessage_Exit)(nil),
		(*AgentStreamMessage_PfReady)(nil),
		(*AgentStreamMessage_PfData)(nil),
		(*AgentStreamMessage_PfClose)(nil),
		(*AgentStreamMessage_PfConnError)(nil),
		(*AgentStreamMessage_PfSessionError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
