// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentStatus represents the health status of an agent.
type AgentStatus int32

const (
	// AGENT_STATUS_UNKNOWN indicates status is not known.
	AgentStatus_AGENT_STATUS_UNKNOWN AgentStatus = 0
	// AGENT_STATUS_HEALTHY indicates the agent is functioning normally.
	AgentStatus_AGENT_STATUS_HEALTHY AgentStatus = 1
	// AGENT_STATUS_DEGRADED indicates the agent is running but experiencing issues.
	AgentStatus_AGENT_STATUS_DEGRADED AgentStatus = 2
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNKNOWN",
		1: "AGENT_STATUS_HEALTHY",
		2: "AGENT_STATUS_DEGRADED",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNKNOWN":  0,
		"AGENT_STATUS_HEALTHY":  1,
		"AGENT_STATUS_DEGRADED": 2,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// OutputType indicates the type of command output.
type OutputType int32

const (
	// OUTPUT_TYPE_UNKNOWN indicates output type is not known.
	OutputType_OUTPUT_TYPE_UNKNOWN OutputType = 0
	// OUTPUT_TYPE_STDOUT indicates standard output.
	OutputType_OUTPUT_TYPE_STDOUT OutputType = 1
	// OUTPUT_TYPE_STDERR indicates standard error.
	OutputType_OUTPUT_TYPE_STDERR OutputType = 2
)

// Enum value maps for OutputType.
var (
	OutputType_name = map[int32]string{
		0: "OUTPUT_TYPE_UNKNOWN",
		1: "OUTPUT_TYPE_STDOUT",
		2: "OUTPUT_TYPE_STDERR",
	}
	OutputType_value = map[string]int32{
		"OUTPUT_TYPE_UNKNOWN": 0,
		"OUTPUT_TYPE_STDOUT":  1,
		"OUTPUT_TYPE_STDERR":  2,
	}
)

func (x OutputType) Enum() *OutputType {
	p := new(OutputType)
	*p = x
	return p
}

func (x OutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (OutputType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x OutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputType.Descriptor instead.
func (OutputType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

// RegisterRequest is sent by the agent to register with central service.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_token is the pre-shared token used to authenticate the agent.
	AgentToken string `protobuf:"bytes,1,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	// cluster_name is the unique name identifying this cluster.
	ClusterName string `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	// metadata contains additional information about the cluster.
	Metadata      *ClusterMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *RegisterRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *RegisterRequest) GetMetadata() *ClusterMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ClusterMetadata contains information about the Kubernetes cluster.
type ClusterMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kubernetes_version is the version of the Kubernetes cluster (e.g., "1.28.0").
	KubernetesVersion string `protobuf:"bytes,1,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	// node_count is the number of nodes in the cluster.
	NodeCount int32 `protobuf:"varint,2,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	// region is the cloud region where the cluster is deployed (e.g., "us-east-1").
	Region string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	// provider is the cloud provider or platform (e.g., "aws", "gcp", "azure", "on-prem").
	Provider      string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMetadata) Reset() {
	*x = ClusterMetadata{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMetadata) ProtoMessage() {}

func (x *ClusterMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMetadata.ProtoReflect.Descriptor instead.
func (*ClusterMetadata) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterMetadata) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *ClusterMetadata) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *ClusterMetadata) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ClusterMetadata) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

// RegisterResponse is returned after an agent registration attempt.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether registration was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// agent_id is a unique identifier assigned to this agent by central.
	// Used in subsequent Heartbeat and ExecuteCommand calls.
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// error_message contains details if registration failed.
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// HeartbeatRequest is sent periodically by the agent to maintain connection.
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id is the identifier assigned during registration.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// status indicates the current health status of the agent.
	Status        AgentStatus `protobuf:"varint,2,opt,name=status,proto3,enum=kbridge.agent.v1.AgentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNKNOWN
}

// HeartbeatResponse is returned in response to a heartbeat.
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// acknowledged indicates the heartbeat was received.
	Acknowledged bool `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// next_heartbeat_seconds indicates how long to wait before the next heartbeat.
	NextHeartbeatSeconds int64 `protobuf:"varint,2,opt,name=next_heartbeat_seconds,json=nextHeartbeatSeconds,proto3" json:"next_heartbeat_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetNextHeartbeatSeconds() int64 {
	if x != nil {
		return x.NextHeartbeatSeconds
	}
	return 0
}

// CommandRequest represents a kubectl command to execute on the agent.
type CommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id is a unique identifier for this command execution.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// agent_id identifies which agent should execute this command.
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// command is the kubectl command arguments (e.g., ["get", "pods", "-o", "wide"]).
	Command []string `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	// namespace is the Kubernetes namespace for the command (optional).
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// timeout_seconds is the maximum time to wait for command completion.
	TimeoutSeconds int32 `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// stdin is optional input to be piped to the command's standard input.
	// Used for commands like "kubectl apply -f -" that read from stdin.
	Stdin         []byte `protobuf:"bytes,6,opt,name=stdin,proto3" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommandRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CommandRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

// CommandResponse contains output from a command execution.
// Multiple responses may be streamed as output is generated.
type CommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id matches the request that generated this response.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// type indicates whether this is stdout or stderr output.
	Type OutputType `protobuf:"varint,2,opt,name=type,proto3,enum=kbridge.agent.v1.OutputType" json:"type,omitempty"`
	// data contains the raw output bytes.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// complete indicates this is the final response for this command.
	Complete bool `protobuf:"varint,4,opt,name=complete,proto3" json:"complete,omitempty"`
	// exit_code is the command's exit code (only set when complete=true).
	ExitCode int32 `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// error_message contains error details if the command failed to execute.
	ErrorMessage  string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandResponse) GetType() OutputType {
	if x != nil {
		return x.Type
	}
	return OutputType_OUTPUT_TYPE_UNKNOWN
}

func (x *CommandResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetPendingCommandsRequest is sent by the agent to poll for commands.
type GetPendingCommandsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id is the identifier assigned during registration.
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingCommandsRequest) Reset() {
	*x = GetPendingCommandsRequest{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingCommandsRequest) ProtoMessage() {}

func (x *GetPendingCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingCommandsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingCommandsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetPendingCommandsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// GetPendingCommandsResponse contains any pending commands for the agent.
type GetPendingCommandsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// commands contains the list of pending commands to execute.
	Commands      []*CommandRequest `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingCommandsResponse) Reset() {
	*x = GetPendingCommandsResponse{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingCommandsResponse) ProtoMessage() {}

func (x *GetPendingCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingCommandsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingCommandsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetPendingCommandsResponse) GetCommands() []*CommandRequest {
	if x != nil {
		return x.Commands
	}
	return nil
}

// SubmitCommandResultRequest is sent by the agent after executing a command.
type SubmitCommandResultRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id matches the command that was executed.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// stdout contains the standard output from the command.
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// stderr contains the standard error from the command.
	Stderr []byte `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// exit_code is the command's exit code.
	ExitCode int32 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// error_message contains error details if the command failed to execute.
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCommandResultRequest) Reset() {
	*x = SubmitCommandResultRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCommandResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCommandResultRequest) ProtoMessage() {}

func (x *SubmitCommandResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCommandResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitCommandResultRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitCommandResultRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubmitCommandResultRequest) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *SubmitCommandResultRequest) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *SubmitCommandResultRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SubmitCommandResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// SubmitCommandResultResponse confirms the result was received.
type SubmitCommandResultResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates the result was accepted.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCommandResultResponse) Reset() {
	*x = SubmitCommandResultResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCommandResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCommandResultResponse) ProtoMessage() {}

func (x *SubmitCommandResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCommandResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitCommandResultResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitCommandResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x10kbridge.agent.v1\"\x94\x01\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\vagent_token\x18\x01 \x01(\tR\n" +
	"agentToken\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName\x12=\n" +
	"\bmetadata\x18\x03 \x01(\v2!.kbridge.agent.v1.ClusterMetadataR\bmetadata\"\x93\x01\n" +
	"\x0fClusterMetadata\x12-\n" +
	"\x12kubernetes_version\x18\x01 \x01(\tR\x11kubernetesVersion\x12\x1d\n" +
	"\n" +
	"node_count\x18\x02 \x01(\x05R\tnodeCount\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\"l\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"d\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.kbridge.agent.v1.AgentStatusR\x06status\"m\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x124\n" +
	"\x16next_heartbeat_seconds\x18\x02 \x01(\x03R\x14nextHeartbeatSeconds\"\xc1\x01\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x14\n" +
	"\x05stdin\x18\x06 \x01(\fR\x05stdin\"\xd4\x01\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.kbridge.agent.v1.OutputTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bcomplete\x18\x04 \x01(\bR\bcomplete\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"6\n" +
	"\x19GetPendingCommandsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"Z\n" +
	"\x1aGetPendingCommandsResponse\x12<\n" +
	"\bcommands\x18\x01 \x03(\v2 .kbridge.agent.v1.CommandRequestR\bcommands\"\xad\x01\n" +
	"\x1aSubmitCommandResultRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"7\n" +
	"\x1bSubmitCommandResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\\\n" +
	"\vAgentStatus\x12\x18\n" +
	"\x14AGENT_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14AGENT_STATUS_HEALTHY\x10\x01\x12\x19\n" +
	"\x15AGENT_STATUS_DEGRADED\x10\x02*U\n" +
	"\n" +
	"OutputType\x12\x17\n" +
	"\x13OUTPUT_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12OUTPUT_TYPE_STDOUT\x10\x01\x12\x16\n" +
	"\x12OUTPUT_TYPE_STDERR\x10\x022\xf5\x03\n" +
	"\fAgentService\x12Q\n" +
	"\bRegister\x12!.kbridge.agent.v1.RegisterRequest\x1a\".kbridge.agent.v1.RegisterResponse\x12T\n" +
	"\tHeartbeat\x12\".kbridge.agent.v1.HeartbeatRequest\x1a#.kbridge.agent.v1.HeartbeatResponse\x12W\n" +
	"\x0eExecuteCommand\x12 .kbridge.agent.v1.CommandRequest\x1a!.kbridge.agent.v1.CommandResponse0\x01\x12o\n" +
	"\x12GetPendingCommands\x12+.kbridge.agent.v1.GetPendingCommandsRequest\x1a,.kbridge.agent.v1.GetPendingCommandsResponse\x12r\n" +
	"\x13SubmitCommandResult\x12,.kbridge.agent.v1.SubmitCommandResultRequest\x1a-.kbridge.agent.v1.SubmitCommandResultResponseB-Z+github.com/why-xn/kbridge/api/proto/agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_agent_proto_goTypes = []any{
	(AgentStatus)(0),                    // 0: kbridge.agent.v1.AgentStatus
	(OutputType)(0),                     // 1: kbridge.agent.v1.OutputType
	(*RegisterRequest)(nil),             // 2: kbridge.agent.v1.RegisterRequest
	(*ClusterMetadata)(nil),             // 3: kbridge.agent.v1.ClusterMetadata
	(*RegisterResponse)(nil),            // 4: kbridge.agent.v1.RegisterResponse
	(*HeartbeatRequest)(nil),            // 5: kbridge.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 6: kbridge.agent.v1.HeartbeatResponse
	(*CommandRequest)(nil),              // 7: kbridge.agent.v1.CommandRequest
	(*CommandResponse)(nil),             // 8: kbridge.agent.v1.CommandResponse
	(*GetPendingCommandsRequest)(nil),   // 9: kbridge.agent.v1.GetPendingCommandsRequest
	(*GetPendingCommandsResponse)(nil),  // 10: kbridge.agent.v1.GetPendingCommandsResponse
	(*SubmitCommandResultRequest)(nil),  // 11: kbridge.agent.v1.SubmitCommandResultRequest
	(*SubmitCommandResultResponse)(nil), // 12: kbridge.agent.v1.SubmitCommandResultResponse
}
var file_agent_proto_depIdxs = []int32{
	3,  // 0: kbridge.agent.v1.RegisterRequest.metadata:type_name -> kbridge.agent.v1.ClusterMetadata
	0,  // 1: kbridge.agent.v1.HeartbeatRequest.status:type_name -> kbridge.agent.v1.AgentStatus
	1,  // 2: kbridge.agent.v1.CommandResponse.type:type_name -> kbridge.agent.v1.OutputType
	7,  // 3: kbridge.agent.v1.GetPendingCommandsResponse.commands:type_name -> kbridge.agent.v1.CommandRequest
	2,  // 4: kbridge.agent.v1.AgentService.Register:input_type -> kbridge.agent.v1.RegisterRequest
	5,  // 5: kbridge.agent.v1.AgentService.Heartbeat:input_type -> kbridge.agent.v1.HeartbeatRequest
	7,  // 6: kbridge.agent.v1.AgentService.ExecuteCommand:input_type -> kbridge.agent.v1.CommandRequest
	9,  // 7: kbridge.agent.v1.AgentService.GetPendingCommands:input_type -> kbridge.agent.v1.GetPendingCommandsRequest
	11, // 8: kbridge.agent.v1.AgentService.SubmitCommandResult:input_type -> kbridge.agent.v1.SubmitCommandResultRequest
	4,  // 9: kbridge.agent.v1.AgentService.Register:output_type -> kbridge.agent.v1.RegisterResponse
	6,  // 10: kbridge.agent.v1.AgentService.Heartbeat:output_type -> kbridge.agent.v1.HeartbeatResponse
	8,  // 11: kbridge.agent.v1.AgentService.ExecuteCommand:output_type -> kbridge.agent.v1.CommandResponse
	10, // 12: kbridge.agent.v1.AgentService.GetPendingCommands:output_type -> kbridge.agent.v1.GetPendingCommandsResponse
	12, // 13: kbridge.agent.v1.AgentService.SubmitCommandResult:output_type -> kbridge.agent.v1.SubmitCommandResultResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
