{{- if .Values.rbac.policy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "controlplane.fullname" . }}-rbac
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
data:
  rbac.yaml: |
    {{- .Values.rbac.policy | nindent 4 }}
{{- end }}
